name: Websites Publisher
on:
  push:
    branches:
      - "main"
jobs:
  website_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Init Domain
        run: echo "www.yazilim.vip" > ./www/CNAME
      - uses: actions/upload-artifact@master
        with:
          name: wwww
          path: www